### PR TITLE
HascalExecutor

### PR DESCRIPTION
**Pull request by pranavbaburaj**
Added a hascal executor for :
 - verifying the source file extension
 - reading the source file
 - tokenizing and parsing
 - write the dlang file

Added an Argument Parser:
 - parser and execute command line functions

### CODE REVIEW

**Comment by pranavbaburaj** [comment]
Please inform me if I should rewrite the `HascalExecutor` or kindly merge it with the `main` branch

**Comment by hasan-kashi** [comment]
Please add used library(modules) in src/core folder and import it from core folder

**Comment by pranavbaburaj** [comment]
What is the need for that??

**Comment by pranavbaburaj** [comment]
I have replaced all external packages(`clint`) with packages present in `src/core/`.

Hope you will merge the commits

Thank you

**Pull request merged**
